language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - php: 5.6
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_Econda
  - secure: PdX0m3hSOdrcRyV9KhRvQ7U3ZTvlsOmAcI69yzF46da/ze0F+SFeN6CiEiaSJV71Xpjux+HSHSNQiaxxYLLnl0Kct6nOxZUeVPJI0l5zS3YB4NIGjzBsiHuuLW9NBFQqzc7Gdf3HkBNsYbnlkG9nUq4iXPIczGhUsm2QLTAjLlEz1X7HmNiJv4eQ5gU8cf8TozivIhVtqyjAZ96a+Zcbb1p3XNLygPgv24h7u+caCjTgQYRt5k8QBvN7SIkWCa4zk5HsOreb706K76CBdBz8m4M6/6lUsA4DX63iOpz6Hq6M1XiViIpWcVpmSOQXUTsILw+7SXO9QM0TY0Arxqj31wVc0w9fKFPWiTElsm8pQS5aaQQr9Bzbp1d4o4QPKMSsAI+DDhBcr7lBXPi7XuIN6r8o8rn07KixAUB0KrrhNjUj0GGIJtSAd2seyEs3EqIaJ8PfBGTcZQCUqO7ZvEfUoX87ydXrw+yOyUiY5MwfJioN12SWmktbHsOr10dhB1l3MlcdEomJadCVKFxqymIRmkLpcJSdUwNe9weyUO4i94A2aIoT+c8NP02MQGUTI9k8sbcQm34quD88hAr56mHkS0Ot/J0iNDWKuOPlH5NxllTMZIj4PKXXrNwmAGsamIM76ZsFw9JJMIlhnI9/Zkom0YCr2mrHpMhpvQcXe5dA/aE=
  - secure: VLZ5SWHENFUDVby2yaN5J12AKBeiKYJddO0pvdS2AHEL0flhKJDb+uMnRLL/tuMMgID4ro/DIVVcT9YdS7+9rv0kuvj9CHP4pSuBaYoasPf0WdRZ3m+LUVtd3TkKISOGLQCVzjTcDbnNN9nQc6zuzfIZIUS/ihiyew2Q+IyEQmTWGn7A8RwGk5Gmv2+nZgaLR0CMGlr71r35x8dh58/MLAv8ZDE9fOthuoUmGSR8q/Pv6bZ8VJjY43j9KQtj+nHgg2//Nu4SohY5zYgkflKcN6HUdPVuIEzyU1VSI9rD1BW+NvuQMkXc/+BSSbZGWIb7/opjCMKS8nft932UQ68vvbHT5qSpAEL2mEML3hy89nQlKqgLqlQu1AtyZq804UOZ5azIWz0T1yjMT5wRACmE+gKkVoz2qt6cEFeqEnOHXoxY7hLHFXsIeIrDX+AOvKWBZahN9tMxM1Kka0nnZiq0u6enRbSTgh417ZajPk3AdoXbR/B/KpJF+QWrjCb4ui04ZfuAhbX8d/sJC1xh/Kc8BkWoHfkm0++ZDsy4FbmgwMA4dXf+N/PEx8cZxvsZ19p65ldG+51/euvcRy+PmEpXpMvrjwt5mjtdsKpqh2KzuNclFbWJhLoyfBHyJQ/K1Goueeh9VswlLYaNppHEVaro8ZO+uDAf/KXPfQziW2QSakI=
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.3
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
before_script:
- composer self-update
- composer install --prefer-source
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: WLrCxiAWks4Uql5e7Iq9K62JXFPZIcLaudyWmowYAyveXUYs5KyBQTB3rCRQ36ezhNqCybtmlPsnE3k+TH/8+6YoLdgYWMfhjs/Iug0/2HCWywHIkO/Mn0GFkya8eGE5AkHknpCnHALKPZy4UmLYBUSIG28uJFP6AZ+pbN87ppwM422SNTivUcuO1uwebrPuULL61IH+q1npSnNp3p+ITORzblfJ3GZZ6kPyE3phONIt/Oi99dBSwTEeJFqd2S3CP+QMSBwySi2TyJ5gSee+T+AYgRNvnIdLY8wpDd3rZ+KKeV8UdCtBjOyCRfy2EWchPZLWLXxtMFC2OkU0DDWjC+uKNa/KVPBdUV1PmmZMLryrAA30JCeXNh3WpzkAu9dW4EkVJOUvw9WxQCIfNgWllz6Sj1ImCv5qluxRfXuWtLmnMeQyfhAa9MdcAPfBPzpoXyGd+T6xtYwfabdLPlWI8q1QnQTKWZig5p41W3PamJyFbLyFiAW4t8tFJ0xVOoGoCmWcb7Cik8S3578rgmuEyTVmZ/Quw4w7yla1EG9Ccdlcmd7u7kIpCAzOwg8bLHb2VO7hmSHfUJ43W3vV759rFh1CYiq4a9S9RRQIZcdv2/OlpupXBWBxdHMpgEOLL6Zr88Te3iYxbpJd5N+lHmkyjz1e2MqvwWCLzJREHTE9Ds4=
notifications:
  slack:
    secure: vr75b0qXXm3ytAMuzuGNbdKCxYC/W1REbMx6BDuqjXJcdQfQuUoLSWMpx6vdQJs/0FcRsA/Uy0K7Sk7OcRgs5twaY5SBoQ0DIdjUNQArT0jiyEDrOSkObQYaFDSzhw39YkkVXQZEjytT2Ge91gGKLsEQ5giX38c5XtHPe/9t0fq9pEzwS9MpeeupAApge0fN4OUOnxv+rOAFnVxFkYGh3aMr/4XbBwA/oUgrKv7uYe/8dgmrZOddqsRWhADxY+xl/I58WDHFkwD/y3ABY+KbA2+gm0muNE13aJZLUK5B4ktKpWeWUystUvJYghJLzJglW1ghao2OWGX+F8FOgViTI4gkU6Xj4h1+yUGdBW87SYzK1BwloTZwkKUoGVTgdYgqyomcEF4955K+SPMhCF+I2VXQFDpTsuaU6LSnkLPefYov4bdQ9csKchkCVjE9+hL6DuMNn8Ffm226bZWhPcdzg3pN/EE51dGiCeStfPYnD5K5PnEZCom7AkSMdZI9cCmeXgioHbWk7ZhGTk7HjQW74l/hVXh3c4i1akSaRvep6qNa+A151lMLyRqwr4PlTy/QLaHKGg+SpM60FouV/o9jmyZUL4GljvbJ3+gGbzFqtGD7sgYADn5LBTwDJzSKxb0eppTQqwGQhW1Qjbjdm+6FZGBRNVEXprbTh1StDf3AA1Q=
