language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_Econda
  - secure: zQUHXKNxRXIgOFVznN2+Z/6l5+UdNs1gXwU1yI881OYzbbmNt+TjaqPu1+5x/grGPQ8EtJQkQNRRgpvGWON2EH50jOSOga6gK7cNEOJGTNs/QJiOrvBIaiSmWJ7rFPSCnmyJXfoOjlaWPYrJd+sPVY5QJAV6zdnwVjdDbU+2hLBT8tsPDM4/yJs7mnZh9R7A3FQJFG6VhT7GrVkLQNS9gNTDzUgFnUUCm1lTwaGLU4cCWo+eLjBXyDBjY1e1jkZNu0CVOZToJUDbZieNV94Rzfe8VLyeKrmCewSFqo+aot/xSpuqNalquy2trLq7pmScNcaQ4LDaiEsS0f0cKat+3FqIJLf1NXZcQR1Q5Imlrzxrw8PTnIP8DAVEDizoahikOPm/A1sYchk5xmVgodCsSqKsyuVYbji4M1bjJuEPRxBZvHRkRrIP2rFM9UItdr4I8URjD6v4F/Tsomonm+PZ92tF7F67xzQ2zf203ujeDIAKKy1RXoV348t4waL3ac4x/mboEq6bIQRsEgGImU5Nuly4XjEngEEShWo3ntMWNvyF+wQxHBuj6QeRHqPUInYdBleG63oihIApBxtrQlt3r34lbRRLJgz55ROz4dv0vpVotc63o1Urhp0+z3qTibFg1PpaPjFc6St5GTpR+u8Av9dmDp10moOoXubcD6EY5yw=
  - secure: hDU82jjNS9JIuv/Q42BAveS78noT2fmHhlybTVFVJdOadFMJDVlJrUExPGEZLeu5pfJ0wzIaOqHK1LNqM9xanzK3prWeABo+k2QYj+D3JqykjJZ+FIQ3BsQ/H1oHlUBHxfb6cA8NDpQl1Qx1r9VrmxyhZQS+Dnxi1lI4x2516GTcYsKdxnRBK3PDeMqBpEtxsdACLz4L0i1YtWoDOpn8Xl5ogO+w+3t+hBsvzC2od0XqDnnv6qyv0DXtGcw3QIuE+mkTd2tH6pwqPWsS2nU9vQD8ICVPuzqiEPMHUo+NZ+1pkXMFSreRtnyYLi7We4JA04UZ7QbAVah8c85SBsnSBw1D/Ys1xICQdFPfWvef+3u0t6EId9nbY9MmG02pvR7l1mbRYQRWZABmL4Y4wIte7Nle2U0beGLF5WjxWNMp0pWQ+dXqDjNSKt+SJhiYRuvcoLLs9oqO1z31phwm/OjI5yJ+AnPBFZbhlEEyWVJYvvjskKJd/Ff34mnzq2ejzjN1MKQBdvQu2QoTF/zwNIc5RGVAiG8GZC9XPrGvOgmp9Hckpf+31wjnZp9KiCiXGsSGxrD+UDD5+GDE4QQHKUoZmzuscC77qVTTp0OBZOnS2OJ6ftVTMLtBejMtraL4NWkV75OGoOw8K6WosUbaOW/q90VdvZ16zOo5XrXjKeEjdMs=
  - secure: j4dSNV31KjnlOHJcK3uZO5V0n5ebS36ttbRd53zYP4cw8IqwFYWtejbqlUS2NaGUKI1dxl6+4XreRSgnpGLJalC6q0zxrpYG+Lm+FILtRGviuzXP/kw8FodO5xpaAQWA4xE/Nxzjv4jFsBMlgzCSSjoGrHs/lAH0rpPSkdXIy2DBsAQ9SnGQYQ55UtX+Xr9PzDAJm/cILeu9eY25gFC/4FmfcSiJ/JnjiWyUJsk6sjO8Vw18yBraT7/5lQwYxqbkvWAHK/zGLaDTssjesGqPdXioiJxXrMAgL7HNV13TTvM30rmFDPNPq4IfzLqDDNGj84W0+ft33Izot5GE5f2Cpb8b7E25Q2US/cGKWsJetyNquHpmcqnW4omqkjSZlZACxIucjCgRCVFuK4NOdGcMhkR4YaLczmE9XqAIFV+VDXXsYfqs25p9bbcLRqwfDjj5UdiWxjiOHIz9xinBxkqbJWcJGhKKoMQZd76+hi53DugmTkEP0RhRTXYHHrQgNXEncAMDa/JaUv1z0TsdsZMEdHIuv2w0Qnpm6Ho+OcOM6ou54teDmLVcv/UhEFfBdj6d9U1CpyoI6JKUguMLXtq3aBvFTkiVyWThYM0Dgx/dpvx0gxBST/4/Lx+As595Z5xrJPv2Wp6p1NzElmkTW3YrVd9mkqBmgxdYpG00QClndAw=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: 0BBiWugPsD51aKIQTMGMAS3+1+KJ+fS1AoaHZ21xWzPm9SxXRBOR8bhfUfKFFnWYAFbCxAxJPImzdBHijPcKSJqic321Lt9yxADZpoPuqelH0/t03AgB5XehSiYrbQF1avfT7AB4OtqMyZwCOXSPRjF8hQx9wA3O31bE88c5VvLCXrIo7hYQ2KF05IUvVeoqYf/xZ/FCqUTdY3dzP0dMdXbTDw7OKE7xSfyefLK4V1Wy2hY9Xex+t0lqnhXnmOFhhhG4Wii7SPDDTTdUNksZVPJAA1M+EM+IieOTIMrGOOOV3yNUIGWrS6D/XdlNMQG3kUr/E2G4mY5fBIhJ+HQsdgxVUxh0Kb2TYbQgscNuY2JnwBD2Uckcx/JqiZCdxB9EKQ23OafYNW0EH45/RyXp/cJDd8pnyEIAL88mQPF60qK4vC8x5VOQ48vBvMpFKBw5hsXfSHiGX/Ff1uDFBxkamS3LJgVoYRE7Zggl3C4gwJ503LhGXssjVe/eIzrd+k3OYkdHowEbIddhvd65Jovu5dOfR0iN02DsSUF6ShhRBP/wT79/S73hG0g7oTJs4MnqcwnPYco9gPEvzjt9dSe+XOBce3oIELKbnMArjwmc0EjIcGTAYtx8pD1E1lR8a0DmBd9TgFJ2UkweTLOpJEAV5pHhAcC+i7xvN9LRPgXnjPs=
notifications:
  slack:
    secure: QxxKwjGxl+sCzMsZlpnIQolZJlUWwuQHqtImufxOSTHvR2GB00H3dWiaOmlKNnZm/Fk4QFcks4GxVz8VhEpmE4f8xmnXLDM8dm7jC69UF3crTFvO8cB4QVuY1E7sRAEvz3oemB5AbMyM/fulJNCU2DhPKuA+6t3itSI0CvMw2Fe3YJjS7cGvFSnbdVXzfMCRZXYOROdslVV8auwe5lLhrg9QmqlAsdGzkRskOy3x2rM4Y3RN83XTHQbzBJBxE433K/cwpsU4ABBHU3BBzzzuvb6fROVja7Eoinv2Jadc2b9Pa9XLGxN5FWsTiSWb6HFDlWdlO8q+RlWDel3C0qmeGwulTDjyTgw07z75hRM3sIZNDyXhDDEMVkQjs7GLN9EQ5qgsQq8uTELlIr2jI/YdQEdyoJzqj41YeBFyZ2kRjRh37gIcGZ6hQA1a3x9fEuwhl9HAaGSzCvQdVkj5HLHUSHvFyhRZfOPrHZNxuslMuxlVgW7PVcEQBXHlPlOL6IamLuLFffy0xZZ8bsliGijxCtLmOlzEQG+ttCzSaI+/NpK1RQrf+UlVkG7FgaF0IQ8+49jYxRrMoy4oo/uqa3byfmfmUXyWZNi2qEYELLHXDTTf8OzdCluUQ6PLjg1FwL5jimXhI9tRvB5iu7J18Gck4FjJajI2+tp+5mdMHdvvnhs=
